---
- name: "Docker check"
  ansible.builtin.include_tasks:
    file: docker_check.yaml
  when: docker_install is defined and docker_install | bool

- name: "Docker install"
  ansible.builtin.include_tasks:
    file: docker_install.yaml
  when: >-
    (docker_install is defined and docker_install) 
    and (docker_is_installed is defined and docker_is_installed.rc != 0 | bool)

- name: "Nvidia"
  ansible.builtin.include_role:
    name: gpu
    tasks_from: nvidia
  when: docker_nvidia is defined and docker_nvidia | bool
